"""Public HLP SDK surface.

Stable embedding path: `HLPHost` / `HLPClient` + first-class objects + adapters.
Industrial helpers (`schema_for`, `negotiate_hlp_version`, permission matchers)
document the HLP-industrial *reference* profile. `Fake*` adapters are for tests.
"""

from __future__ import annotations

from .adapters import (
    AgentAdapter,
    AgentAdapterError,
    AgentRunHandle,
    ClaudeCodeCLIAdapter,
    CodexCLIAdapter,
    CodexHarnessAdapter,
    CrewAIAdapter,
    FakeAgentAdapter,
    FakeHarnessAdapter,
    HarnessAdapter,
    HarnessCapabilities,
    HarnessEvent,
    HarnessEventDelivery,
    HermesCLIAdapter,
    HermsCLIAdapter,
    InMemoryAgentAdapter,
    KimiCLIAdapter,
    LangGraphAdapter,
    OpenAIAgentsSDKAdapter,
    OpenAIPythonSDKAdapter,
    PiHarnessAdapter,
    ProcessAgentAdapter,
    ProcessResult,
    PromptCLIAdapter,
    PythonCallableAgentAdapter,
    ReliableHarnessEventAdapter,
)
from .audit import AuditEvent, AuditLog
from .events import EventBus, HLPEvent, InMemoryEventBus
from .host import HLPHost
from .objects import (
    AdapterOperationContext,
    AdapterOutboxRecord,
    Artifact,
    ArtifactPayload,
    ArtifactProvenance,
    ArtifactRef,
    Checkpoint,
    CheckpointOption,
    CheckpointResolution,
    Constraints,
    ControlSignal,
    Evidence,
    ExternalRef,
    HumanInboxItem,
    IdempotencyRecord,
    InputRef,
    InteractionRef,
    Ledger,
    LedgerEntry,
    Ownership,
    OwnershipTransfer,
    PermissionGrant,
    ProposedAction,
    Review,
    ReviewComment,
    SteeringAmendment,
    Task,
    TaskSpec,
)
from .operations import HumanLoopOperations
from .permissions import (
    is_permission_scope_pre_authorized,
    normalize_permission_scope,
    permission_scope_matches,
)
from .realtime import (
    SoftPromotionResult,
    assert_soft_does_not_change_task_state,
    control_signal_to_wire,
    may_resolve_hard_checkpoint_with_signal,
    merge_soft_control_signals,
    promotion_audit_payload,
    require_hard_resolve_allowed,
)
from .schema import (
    HLP_JSON_SCHEMAS,
    VersionNegotiationResult,
    negotiate_hlp_version,
    schema_for,
    to_wire,
    validate_wire_object,
)
from .sdk import HLPClient
from .sqlite_store import SQLiteHumanLoopStore
from .state_machine import (
    LEGAL_TRANSITIONS,
    TERMINAL_STATES,
    check_transition,
    is_legal,
)
from .store import HumanLoopStore
from .types import (
    HLP_PROFILE,
    HLP_REALTIME_PROFILE,
    HLP_REALTIME_SPEC_VERSION,
    HLP_SCHEMA_VERSION,
    HLP_SPEC_VERSION,
    AutonomyTier,
    CheckpointKind,
    CheckpointResolutionAction,
    CheckpointState,
    ErrorCode,
    HarnessConformance,
    HarnessEventKind,
    HumanInboxAction,
    HumanInboxKind,
    OwnershipTransferVia,
    PermissionGrantDecision,
    ProposedActionRisk,
    ProtocolError,
    ReviewCommentSeverity,
    ReviewKind,
    ReviewVerdict,
    SteeringIntent,
    TaskState,
)

__all__ = [
    "AgentAdapter",
    "AgentAdapterError",
    "AgentRunHandle",
    "AdapterOperationContext",
    "AdapterOutboxRecord",
    "Artifact",
    "ArtifactPayload",
    "ArtifactProvenance",
    "ArtifactRef",
    "AuditEvent",
    "AuditLog",
    "ClaudeCodeCLIAdapter",
    "Checkpoint",
    "CheckpointOption",
    "CheckpointResolution",
    "Constraints",
    "ControlSignal",
    "CodexCLIAdapter",
    "CodexHarnessAdapter",
    "CrewAIAdapter",
    "ErrorCode",
    "EventBus",
    "Evidence",
    "ExternalRef",
    "FakeAgentAdapter",
    "FakeHarnessAdapter",
    "HarnessAdapter",
    "HarnessCapabilities",
    "HarnessConformance",
    "HarnessEvent",
    "HarnessEventDelivery",
    "HarnessEventKind",
    "HLP_JSON_SCHEMAS",
    "HLP_PROFILE",
    "HLP_REALTIME_PROFILE",
    "HLP_REALTIME_SPEC_VERSION",
    "HLP_SCHEMA_VERSION",
    "HLP_SPEC_VERSION",
    "HermesCLIAdapter",
    "HermsCLIAdapter",
    "HLPClient",
    "HLPHost",
    "HLPEvent",
    "HumanLoopOperations",
    "HumanLoopStore",
    "HumanInboxItem",
    "HumanInboxAction",
    "HumanInboxKind",
    "InMemoryAgentAdapter",
    "InMemoryEventBus",
    "InputRef",
    "IdempotencyRecord",
    "InteractionRef",
    "is_permission_scope_pre_authorized",
    "KimiCLIAdapter",
    "Ledger",
    "LedgerEntry",
    "LangGraphAdapter",
    "OpenAIAgentsSDKAdapter",
    "OpenAIPythonSDKAdapter",
    "PiHarnessAdapter",
    "Ownership",
    "OwnershipTransfer",
    "PermissionGrant",
    "permission_scope_matches",
    "normalize_permission_scope",
    "ProposedAction",
    "ProcessAgentAdapter",
    "ProcessResult",
    "PromptCLIAdapter",
    "ProtocolError",
    "PythonCallableAgentAdapter",
    "ReliableHarnessEventAdapter",
    "Review",
    "ReviewComment",
    "SoftPromotionResult",
    "SteeringAmendment",
    "SQLiteHumanLoopStore",
    "Task",
    "TaskSpec",
    "TaskState",
    "CheckpointKind",
    "CheckpointState",
    "CheckpointResolutionAction",
    "OwnershipTransferVia",
    "AutonomyTier",
    "PermissionGrantDecision",
    "ProposedActionRisk",
    "ReviewKind",
    "ReviewVerdict",
    "ReviewCommentSeverity",
    "SteeringIntent",
    "VersionNegotiationResult",
    "assert_soft_does_not_change_task_state",
    "control_signal_to_wire",
    "may_resolve_hard_checkpoint_with_signal",
    "merge_soft_control_signals",
    "negotiate_hlp_version",
    "promotion_audit_payload",
    "require_hard_resolve_allowed",
    "schema_for",
    "to_wire",
    "validate_wire_object",
    "LEGAL_TRANSITIONS",
    "TERMINAL_STATES",
    "check_transition",
    "is_legal",
]
