"""HLP-first public SDK surface.

`loops` is the public entry point for Human Loop Protocol (HLP): protocol
objects, SDK, adapters, and the embedding host. The lower-level `loops.loop0`
runtime remains available as an internal/minimal runtime package, but it is not
the top-level product API.
"""

from __future__ import annotations

from loops.hlp import (
    AgentAdapter,
    AgentAdapterError,
    AgentRunHandle,
    Artifact,
    ArtifactPayload,
    ArtifactProvenance,
    ArtifactRef,
    AuditEvent,
    AuditLog,
    Checkpoint,
    CheckpointOption,
    CheckpointResolution,
    ClaudeCodeCLIAdapter,
    CodexCLIAdapter,
    Constraints,
    CrewAIAdapter,
    ErrorCode,
    EventBus,
    Evidence,
    FakeAgentAdapter,
    HLPClient,
    HLPEvent,
    HLPHost,
    HermesCLIAdapter,
    HermsCLIAdapter,
    HumanLoopOperations,
    HumanLoopStore,
    InMemoryAgentAdapter,
    InMemoryEventBus,
    InputRef,
    LangGraphAdapter,
    Ledger,
    LedgerEntry,
    OpenAIAgentsSDKAdapter,
    OpenAIPythonSDKAdapter,
    Ownership,
    OwnershipTransfer,
    ProcessAgentAdapter,
    ProcessResult,
    ProtocolError,
    PythonCallableAgentAdapter,
    Review,
    ReviewComment,
    SQLiteHumanLoopStore,
    Task,
    TaskSpec,
)

__all__ = [
    "AgentAdapter",
    "AgentAdapterError",
    "AgentRunHandle",
    "Artifact",
    "ArtifactPayload",
    "ArtifactProvenance",
    "ArtifactRef",
    "AuditEvent",
    "AuditLog",
    "Checkpoint",
    "CheckpointOption",
    "CheckpointResolution",
    "ClaudeCodeCLIAdapter",
    "CodexCLIAdapter",
    "Constraints",
    "CrewAIAdapter",
    "ErrorCode",
    "EventBus",
    "Evidence",
    "FakeAgentAdapter",
    "HLPClient",
    "HLPEvent",
    "HLPHost",
    "HermesCLIAdapter",
    "HermsCLIAdapter",
    "HumanLoopOperations",
    "HumanLoopStore",
    "InMemoryAgentAdapter",
    "InMemoryEventBus",
    "InputRef",
    "LangGraphAdapter",
    "Ledger",
    "LedgerEntry",
    "OpenAIAgentsSDKAdapter",
    "OpenAIPythonSDKAdapter",
    "Ownership",
    "OwnershipTransfer",
    "ProcessAgentAdapter",
    "ProcessResult",
    "ProtocolError",
    "PythonCallableAgentAdapter",
    "Review",
    "ReviewComment",
    "SQLiteHumanLoopStore",
    "Task",
    "TaskSpec",
]
