"""HLP-first public SDK surface.

`loops` is the public entry point for Human Loop Protocol (HLP): protocol
objects, SDK, adapters, and the embedding host. Execution harnesses stay
external and connect through HLP adapter contracts.

Public surface groups (all still re-exported for compatibility):

- **stable core**: `HLPHost`, `HLPClient`, first-class objects, `ProtocolError`
- **adapters**: contracts plus first-class / shape-compatible / testing adapters
- **industrial helpers**: schema / version negotiation / permission helpers
- **realtime helpers**: ControlSignal merge/promotion (HLP-realtime appendix C)
- **advanced / internal-friendly**: `HumanLoopOperations`, stores, state helpers

Prefer `HLPHost` / `HLPClient` for application embedding. Prefer first-class
CLI adapters for real harness work; treat framework adapters as shims.
"""

from __future__ import annotations

from loops.hlp import (
    AgentAdapter,
    AgentAdapterError,
    AgentRunHandle,
    AdapterOperationContext,
    AdapterOutboxRecord,
    Artifact,
    ArtifactPayload,
    ArtifactProvenance,
    ArtifactRef,
    AuditEvent,
    AuditLog,
    Checkpoint,
    CheckpointOption,
    CheckpointResolution,
    ClaudeCodeCLIAdapter,
    CodexCLIAdapter,
    CodexHarnessAdapter,
    Constraints,
    ControlSignal,
    CrewAIAdapter,
    ErrorCode,
    EventBus,
    Evidence,
    ExternalRef,
    FakeAgentAdapter,
    FakeHarnessAdapter,
    HarnessAdapter,
    HarnessCapabilities,
    HarnessConformance,
    HarnessEvent,
    HarnessEventDelivery,
    HarnessEventKind,
    HLP_JSON_SCHEMAS,
    HLP_PROFILE,
    HLP_SCHEMA_VERSION,
    HLP_SPEC_VERSION,
    HLPClient,
    HLPEvent,
    HLPHost,
    HermesCLIAdapter,
    HermsCLIAdapter,
    HumanLoopOperations,
    HumanLoopStore,
    HumanInboxItem,
    HumanInboxAction,
    HumanInboxKind,
    InMemoryAgentAdapter,
    InMemoryEventBus,
    InputRef,
    IdempotencyRecord,
    InteractionRef,
    is_permission_scope_pre_authorized,
    KimiCLIAdapter,
    LangGraphAdapter,
    Ledger,
    LedgerEntry,
    OpenAIAgentsSDKAdapter,
    OpenAIPythonSDKAdapter,
    PiHarnessAdapter,
    Ownership,
    OwnershipTransfer,
    PermissionGrant,
    permission_scope_matches,
    normalize_permission_scope,
    ProposedAction,
    ProcessAgentAdapter,
    ProcessResult,
    PromptCLIAdapter,
    ProtocolError,
    PythonCallableAgentAdapter,
    ReliableHarnessEventAdapter,
    Review,
    ReviewComment,
    SoftPromotionResult,
    SQLiteHumanLoopStore,
    SteeringAmendment,
    Task,
    TaskSpec,
    VersionNegotiationResult,
    assert_soft_does_not_change_task_state,
    control_signal_to_wire,
    may_resolve_hard_checkpoint_with_signal,
    merge_soft_control_signals,
    negotiate_hlp_version,
    promotion_audit_payload,
    require_hard_resolve_allowed,
    schema_for,
    to_wire,
    validate_wire_object,
)

__all__ = [
    "AgentAdapter",
    "AgentAdapterError",
    "AgentRunHandle",
    "AdapterOperationContext",
    "AdapterOutboxRecord",
    "Artifact",
    "ArtifactPayload",
    "ArtifactProvenance",
    "ArtifactRef",
    "AuditEvent",
    "AuditLog",
    "Checkpoint",
    "CheckpointOption",
    "CheckpointResolution",
    "ClaudeCodeCLIAdapter",
    "CodexCLIAdapter",
    "CodexHarnessAdapter",
    "Constraints",
    "ControlSignal",
    "CrewAIAdapter",
    "ErrorCode",
    "EventBus",
    "Evidence",
    "ExternalRef",
    "FakeAgentAdapter",
    "FakeHarnessAdapter",
    "HarnessAdapter",
    "HarnessCapabilities",
    "HarnessConformance",
    "HarnessEvent",
    "HarnessEventDelivery",
    "HarnessEventKind",
    "HLP_JSON_SCHEMAS",
    "HLP_PROFILE",
    "HLP_SCHEMA_VERSION",
    "HLP_SPEC_VERSION",
    "HLPClient",
    "HLPEvent",
    "HLPHost",
    "HermesCLIAdapter",
    "HermsCLIAdapter",
    "HumanLoopOperations",
    "HumanLoopStore",
    "HumanInboxItem",
    "HumanInboxAction",
    "HumanInboxKind",
    "InMemoryAgentAdapter",
    "InMemoryEventBus",
    "InputRef",
    "IdempotencyRecord",
    "InteractionRef",
    "is_permission_scope_pre_authorized",
    "KimiCLIAdapter",
    "LangGraphAdapter",
    "Ledger",
    "LedgerEntry",
    "OpenAIAgentsSDKAdapter",
    "OpenAIPythonSDKAdapter",
    "PiHarnessAdapter",
    "Ownership",
    "OwnershipTransfer",
    "PermissionGrant",
    "permission_scope_matches",
    "normalize_permission_scope",
    "ProposedAction",
    "ProcessAgentAdapter",
    "ProcessResult",
    "PromptCLIAdapter",
    "ProtocolError",
    "PythonCallableAgentAdapter",
    "ReliableHarnessEventAdapter",
    "Review",
    "ReviewComment",
    "SoftPromotionResult",
    "SQLiteHumanLoopStore",
    "SteeringAmendment",
    "Task",
    "TaskSpec",
    "VersionNegotiationResult",
    "assert_soft_does_not_change_task_state",
    "control_signal_to_wire",
    "may_resolve_hard_checkpoint_with_signal",
    "merge_soft_control_signals",
    "negotiate_hlp_version",
    "promotion_audit_payload",
    "require_hard_resolve_allowed",
    "schema_for",
    "to_wire",
    "validate_wire_object",
]
